create TABLE survey(
	s_id int(8) NOT NULL,
	name varchar(50),
	address TEXT,
	apt varchar(15),
	city varchar(30),
	state varchar(30),
	zip int(10),
	telephone varchar(12),
	email varchar(100),
	blog_url TEXT,
	survey_date varchar(20),
	campus varchar(100),
	university varchar(20),
	comments TEXT,
	graduation varchar(20),
	recommendation varchar(15),
	data varchar(100),
	UNIQUE(s_id),
	PRIMARY KEY(s_id)
)